### PR TITLE
Plot refactor

### PR DESCRIPTION
**Pull request by dwf**
*To be merged after rebasing on top of master after #32 is merged.*

 * Break out a base class for other Bokeh-interacting Extensions.
 * Manipulate Session and Document objects instead of relying on stateful bokeh.plotting interface.
 * Get rid of open_browser as the signature had changed and so it that wasn't working anyway.

### CODE REVIEW

**Comment by dwf** [comment]
If anyone can give this a look, it'd be helpful.

**Comment by rizar** [comment]
David, we are awfully sorry, both Dima S and I are rushing for ICLR deadline... Please give us time until Monday to sort this shit out, and I promise, this PR will be on my very high priority list after that.

**Comment by dwf** [comment]
I figured as much, no problem.

**Comment by dwf** [comment]
@rizar Any objection to merging this? It still only works with Bokeh 0.9 but it contains a number of fixes that I've been using for a while and in particularly fixes unpickling and resumption of jobs with a Plot extension.

**Comment by rizar** [comment]
Do you mean 0.10? I thought 0.9 was a particularly bad version for us...

**Comment by dwf** [comment]
Yes sorry 0.10.

**Comment by rizar** [comment]
Honestly, I do not know Bokeh well enough to confidently review the last commit. Just go ahead and merge :)

**Comment by dwf** [comment]
@ddtm I think you might benefit from this. You said you were having job resumption issues of some sort.

**Comment by dwf** [comment]
(Specifically a JSON decode error upon resuming)

**Pull request merged**
