### PR TITLE
Ensure compatibility with Bokeh 0.10

### PR DESCRIPTION
**Pull request by rizar**
Bokeh 0.10 has been released! The only thing left is to ensure that we are compatible with it.

### CODE REVIEW

**Comment by rizar** [comment]
One unfortunate thing about this PR is  that at least with Bokeh 0.10 it gives the following error, even though it  does not crash and plots fine:

```
ERROR:/home/rizar/.local/lib/python2.7/site-packages/bokeh/validation/check.pyc:W-1001 (NO_GLYPH_RENDERERS): Plot has no glyph renderers: Figure, ViewModel:Plot, ref _id: c22a9321-7ee2-4945-be76-7aca351861a0
```

@dwf , any ideas?

**Comment by rizar** [comment]
I just realized that the Plot extension is not even in Blocks-extras. I am going to fix that before moving forward with this PR.

**Comment by rizar** [comment]
@dmitriy-serdyuk , @dwf , this is ready for review!

**Comment by dmitriy-serdyuk** [comment]
LGTM. Do you still have that error?

**Comment by rizar** [comment]
I still have this error, but now I understand why.

We have two types of monitoring in MNIST demo. `DataStreamMonitoring` is run before the first epoch. `TrainingDataMonitoring`, obviously, isn't, because that makes no sense. However, `Plot` is called before the first epoch. So it has nothing to plot in some of channels.

I do not know how to fix this, because in general it makes a lot of sense to display validation cost before the first epoch.

**Comment by rizar** [comment]
But I don't like the idea of holding this PR for this reason, because people have not been able to use Bokeh for a few months.

**Pull request merged**
