### PR TITLE
Rename the package to blocks_extras

### PR DESCRIPTION
**Pull request by rizar**
First step towards getting rid of namespace packages.

### CODE REVIEW

**Comment by rizar** [comment]
Also see https://github.com/mila-udem/blocks-examples/pull/68.

Waiting for a merge permission. After this PR is merged, namespace packages support can be removed from Blocks.

**Comment by rizar** [comment]
Looking for people willing to review this.

@bartvm , @dwf , @dmitriy-serdyuk

**Comment by rizar** [comment]
@bartvm , can you please review this PR?

**Comment by bartvm** [comment]
LGTM but the readme requires a quick update (it talks about namespace packages at the bottom, which you can just remove I guess).

**Pull request merged**
