### PR TITLE
Add FixedPermutation and PermutationMatrix.

### PR DESCRIPTION
**Pull request by dwf**

### CODE REVIEW

**Comment by rizar** [comment]
I am confused, did we decide to test `blocks-extras` or not?

**Comment by rizar** [comment]
Since this is `blocks-extras` I did not try too hard to read it, but it looks all right. I would not put in `__init__.py` though, imagine how huge it will grow when people start actually contributing here. Maybe `bricks/permutation.py`?

**Comment by bartvm** [comment]
Yes, blocks-extras is tested (tests are also run as part of the Travis run for the core)

**Comment by rizar** [comment]
Unfortunately https://travis-ci.org/mila-udem/blocks-extras/builds/64037116 gives `Could not find .travis.yml, using standard configuration.` And there is no `travis.yml` in master in fact.

**Comment by bartvm** [comment]
Probably forgot to commit that then, I'll do it when I'm back in Montreal
tonight

**Comment by rizar** [comment]
Sure, no rush :)

**Comment by dwf** [comment]
Guess I'll have to rebase this after #3. Please remind me if I don't.

**Comment by bartvm** [comment]
Rebase away!

**Comment by dwf** [comment]
@bartvm Rebased.

**Pull request merged**
