### PR TITLE
Try to fix tests by not installing Bokeh dependencies

### LINKED ISSUE #25: Tests are failing
See https://travis-ci.org/mila-udem/blocks-extras/jobs/84567600#L140

It looks like a Conda problem, because both pandas and numpy are installed by conda, but somehow they turn out to be not binary compatible.

### PR DESCRIPTION
**Pull request by rizar**
Trying  to fix #25

### CODE REVIEW

**Comment by bartvm** [comment]
Why not just add bokeh to `req-travis-conda.txt` with a pinned version?

**Comment by bartvm** [comment]
(And then just merge the two requirements file with `cat`, to clarify)

**Comment by rizar** [comment]
Because we still install all dependencies from `requirements.txt` from Blocks after that, see [this line](https://github.com/mila-udem/blocks-extras/blob/master/.travis.yml#L25). I guess we should somehow installed a pinned version of Bokeh and insist that no packages are updated, but somehow `--no-update-dependencies` does not work for me in #27

**Comment by bartvm** [comment]
Well, strictly we don't even need to install that `requirements.txt` (everything should be installed already with `req-travis-conda.txt`). That said, I don't understand the problem? If you create a file `req-travis-conda.txt` with the contents `bokeh==0.10` and then do this in `.travis.yml`:

```yaml
- curl https://raw.githubusercontent.com/mila-udem/blocks/master/req-travis-conda.txt >> req-travis-conda.txt
- conda install -q --yes python=$TRAVIS_PYTHON_VERSION --file req-travis-conda.txt
```
The added bonus is that you can be sure that dependencies aren't duplicated between `blocks-extras` and Blocks.

**Comment by bartvm** [comment]
Looks like you did exactly that the same time I pressed the comment button :p I would use a separate file because it's consistent with the other repos (and scales more easily to possible future dependencies), but otherwise I think this solution should work.

**Comment by rizar** [comment]
I agree that a separate file makes sense. But I fail to understand why we install Blocks with `requirements.txt` on Travis, even though we have a special file `req-travis-pip.txt` for that.

**Comment by bartvm** [comment]
I guess the idea is that `-r requirements.txt` should not do anything. If it does it means that we are either missing dependencies in `req-travis-*.txt`, or the dependencies have gotten out of sync. If there are syntax errors in `requirements.txt` those would show up as well.

**Comment by rizar** [comment]
In this case we should install them without `-q`, so that we at least saw that something is done by visual inspection of the log.

Feel free to merge this PR.

**Comment by bartvm** [comment]
Agreed, the installation of blocks itself should really be done without `-q`.

**Pull request merged**
